using UnityEngine;
using UnityEngine.InputSystem;

namespace Player.Combat
{
	public class CombatInputHelper : MonoBehaviour
	{
		// this is the c# class generated by the input system asset
		private PlayerControls _playerControls;
		
		//this is the class that handles all the combat values that this object receives via the input system events
		private PlayerCombat _combat;

		private void Awake()
		{
			_playerControls = new PlayerControls();
		}

		private void OnEnable()
		{
			_playerControls.Player.LightAttack.performed += OnLightAttack;
			_playerControls.Player.LightAttack.Enable();
		}

		private void OnDisable()
		{
			_playerControls.Player.LightAttack.performed -= OnLightAttack;
			_playerControls.Player.LightAttack.Disable();
		}

		private void Start()
		{
			_combat = GetComponent<PlayerCombat>();
		}

		private void OnLightAttack(InputAction.CallbackContext context)
		{
			_combat.OnLightAttackInput();
		}
	}
}