using UnityEngine;
using UnityEngine.InputSystem;

namespace Player.Combat
{
	public class PlayerInputHelper : MonoBehaviour
	{
		// this is the c# class generated by the input system asset
		private PlayerControls _playerControls;
		
		//this is the class that handles all the combat values that this object receives via the input system events
		private PlayerInput _input;
		
		private InputAction _use;

		private void Awake()
		{
			_playerControls = new PlayerControls();
		}

		private void OnEnable()
		{
			_playerControls.Player.LightAttack.performed += OnLightAttack;
			_playerControls.Player.LightAttack.Enable();
			_playerControls.Player.Use.performed += OnUse;
			_playerControls.Player.Use.Enable();
		}

		private void OnDisable()
		{
			_playerControls.Player.LightAttack.performed -= OnLightAttack;
			_playerControls.Player.LightAttack.Disable();
			
			_playerControls.Player.Use.performed += OnUse;
			_playerControls.Player.Use.Disable();
		}

		private void Start() => _input = GetComponent<PlayerInput>();

		private void OnLightAttack(InputAction.CallbackContext context) => _input.OnLightAttackInput();

		private static void OnUse(InputAction.CallbackContext context) => PlayerInput.InvokeUsePressed();
	}
}